### ISSUE TITLE
Upgrade D3?

### ISSUE THREAD

**Issue by thieman** [jondot/graphene#11]
Hi there,

I just started playing around a bit with Graphene and put together a fairly robust dashboard pretty quickly. Thanks! One question, though: my Y axes are running into an SI formatting bug from D3. They fixed it and pushed it to master yesterday as part of 2.9.2. It looks like the version of D3 included with Graphene is 2.7.2. Any plans to upgrade so we can get the fixes they've made in the last three months?

Thanks,
Travis

**Comment by jondot** [comment]
Hi,
Very happy to hear about your experience!
I think it should be fairly easy to do that, I'll schedule some time tomorrow to work on it.

Thanks for bringing it up!

**Comment by cognusion** [comment]
I removed d3.time.js, and copied the new d3.v2.min.js in place of d3.js, cleared caches, and everything just worked. Will submit a pull request shortly.

**Comment by jondot** [comment]
@cognusion thanks I've pulled it in, and also testing it out on some of my dashboards, works great!
