### ISSUE TITLE
Bar charts

### ISSUE THREAD

**Issue by dennisvdvliet** [jondot/graphene#16]
Any plans to start doing bar charts in the near future?

Or would that make a nice pull request?

D

**Comment by jondot** [comment]
Hi Dennis,
I'm not in direct need for it right now personally, but it would be extremely nice to have :)
Let me know if you want to attempt doing it, and I will gladly help with what I can

**Comment by dennisvdvliet** [comment]
Will give it a try somewhere this week.

Any way I can speed up build speed for coffee, it seems to be lagging for a few seconds every time I make a change.

**Comment by jondot** [comment]
Great!
Yup, turn off minification. Look in `Guardfile` for this line:

```
guard 'sprockets', :destination => "build", :asset_paths => ['app', '.'], :minify => true do
```

Then just remove `, :minify => true`.
