### ISSUE TITLE
Example is misconfigured

### ISSUE THREAD

**Issue by honza** [jondot/graphene#17]
The example dashboard doesn't work for me out of the box. There are no Javascript errors in the console. There are no 404s. I did however notice that the `index.css` file is served empty. I'm not a Ruby guy so I'm not sure how to fix this issue.

**Comment by jondot** [comment]
Correct, my apologies.
Will push a fix in a few more minutes
Thanks!

**Comment by honza** [comment]
Sweet, works great. Thanks a lot!
