### ISSUE TITLE
in demo mode, models can't find data source

### ISSUE THREAD

**Issue by jondot** [jondot/graphene#21]
Looks like this one was introduced during one of the changes for allowing multiple data models.
Need to resolve by getting a 'Demo' version of View.model.

**Comment by friedhelm-langhof** [comment]
It seams there is no server open on Port 4567, just handling Ressources on Port 4000. Even in Dev Mode there is no Rest-/Json-Server or sth. So i get a 404 at 
http://localhost:4567/&jsonp=jQueryXXXXXXXXXXXXXXXX_XXXXXXXXXXXXXx?_=XXXXXXXXXXXXXXXX

Any suggestions?

**Comment by tibbon** [comment]
I too am experiencing the same thing here. Is this expected behavior?

**Comment by jondot** [comment]
Hi guys, sorry for the late response.
Looks like this was introduced when supporting additional views, I've bumped into it before and the reason is known, however what yoi're describing (Json-Server) is new to me.
Thanks for pointing it out, I'll check that ASAP.

**Comment by jondot** [comment]
Demo mode should work now. Took me way to long to get to this but I hope for forgiveness :)
