### ISSUE TITLE
Gauge type: current

### ISSUE THREAD

**Issue by vrish88** [jondot/graphene#28]
Is there a way to display the latest data point on a gauge label or gadget? Something like:

``` javascript
var description = {
  "Current Speed": {
    source: "http://localhost:4567/",
    GaugeLabel: {
      parent: "#hero-one",
      title: "Your speed is",
      type: "current"
    }
  }
}
```

**Comment by jondot** [comment]
Looks like you already implemented it yourself, I salute you :)

**Comment by FredLliao** [comment]
hello,I want to get the sum of the latest day data point on a gauge lable,something like:
var description = {
  "The Sum": {
    source: "http://localhost:4567/",
    GaugeLabel: {
      parent: "#hero-one",
      title: "The Sum is",
      type: "sum"
    }
  }
}

how to do it?Thank you!
