### ISSUE TITLE
Graphene showing no graphs

### ISSUE THREAD

**Issue by luckyhughes** [jondot/graphene#53]
Hi,

I am new to Graphene. According to instructions I cloned graphene and copied the graphene folder to webapps folder in Graphite.

Now i tried accessing the .../example/dashboard.html from browser. I can see the page but don't see any graphs with sample data. It just shows me message as follows

A D3.js, Backbone.js based Graphite Dashboard Toolkit.

Could you help me if i am missing anything. could you please send me instruction as what i need to do please.

Thanks in advance.

--Sandeep

**Comment by jondot** [comment]
Hi & welcome!

To see the demo, you probably need to run the local http proxy.

```
$ gem install serve
$ serve .
```

This will create a local HTTP server that serves your files from disk.
Then with your browser go to `http://localhost:4000/` and find the `example/dashboard.html` file.

Then it should work.

Let me know if you need further instructions

**Comment by luckyhughes** [comment]
Thanks. I am having trouble installing serve using gem. Can I use apache web server?

**Comment by jondot** [comment]
Yes, sure. You can also try `python -m SimpleHTTPServer 4000` if you have python installed.

**Comment by luckyhughes** [comment]
This should be helpful. I would try this and post you findings.

**Comment by luckyhughes** [comment]
Thanks a lot. It works.

**Comment by luckyhughes** [comment]
Now, I have trouble viewing graphite data in graphene. I added new metrics in example-dash.js. but i is not displaying graphite data.

"Sandeep-Test": {
      source: "http://graphite-hostname:8080/render?from=-2hours&until=now&width=400&height=250&target=statsite.kv.servers.sv5bench4-app.cpu.total.system&format=json",
      TimeSeries: {
        parent: '#g2-2',
      }
     },

**Comment by jondot** [comment]
Hi Sandeep, looks like it should work. Do you have any errors in your browser's Javascript console?

**Comment by luckyhughes** [comment]
Thanks Dotan, I can see graphs now in Graphene.

**Comment by jondot** [comment]
Great!
