### ISSUE TITLE
Graphene TimeSeries data for PHP

### ISSUE THREAD

**Issue by eeshamca** [jondot/graphene#55]
Hello,
I want to do prepare a timeseries chart for dynamic data ? 
Is this Graphene is working for PHP ? or its suits for Ruby ?

**Comment by jondot** [comment]
Hi,
Graphene is client-side completely.
All you need is a working Graphite service somewhere.
http://graphite.wikidot.com/

**Comment by jondot** [comment]
Closing up, reopen if you still have issues here :+1:
