### ISSUE TITLE
Gauge type: sum

### ISSUE THREAD

**Issue by FredLliao** [jondot/graphene#56]
Is there a way to display the total data point on a gauge label or gadget? Something like:

var description = {
  " The Sum": {
    source: "http://localhost:4567/",
    GaugeLabel: {
      parent: "#hero-one",
      title: "The Sum is",
      type: "sum"
    }
  }
}

**Comment by jondot** [comment]
Hi,
Such computation over time-series is best left to Graphite itself. You can do this very simply if on Graphite you do `sum(your-time-series)` and then take a `GaugeLabel` with type `max`.
This is what I've done many times as well.

Feel free to let me know how it goes

**Comment by jondot** [comment]
Closing this one, feel free to open if you still have problems :)
