### ISSUE TITLE
GaugeGadget not changing

### ISSUE THREAD

**Issue by organicveggie** [jondot/graphene#6]
Could you clarify how to properly hook up a _GaugeGadget_? I have both a _GaugeLabel_ and _GaugeGadget_ using the same source data from Graphite. The _GaugeLabel_ works perfectly, but the _GaugeGadget_ just stays steady at 0.

I based this off the `example-dash.js` file:

``` javascript
    "Overall Request Rate": {
      source: "http://graphite.example.com/render?from=-1hours&until=now&width=400&height=250&target=alias(sum(prod.web*.com.example.server.MyService.webapp-OverallRequestRate.1MinuteRate)%2C%22Webapp%20Requests%2FSecond%22)&title=Request_Rate&uniq=0.05719376518391073&format=json",
      GaugeLabel: {
        parent: "#hero-one",
        title: "Requests / Second"
      }
    },
    "Overall Request Rate Gadget": {
      source: "http://graphite.example.com/render?from=-1hours&until=now&width=400&height=250&target=alias(sum(prod.web*.com.example.server.MyService.webapp-OverallRequestRate.1MinuteRate)%2C%22Webapp%20Requests%2FSecond%22)&title=Request_Rate&uniq=0.05719376518391073&format=json",
      GaugeGadget: {
        parent: "#hero-one",
        title: "Requests"
      }
    },
```

Anything obvious I might be missing?

**Comment by jondot** [comment]
Hi, your config looks right, can you please provide the data series for the gauge gadget?

**Comment by organicveggie** [comment]
Thanks. Good to know that I'm on the right track. :)

I dumped the data series as JSON into a Gist:

https://gist.github.com/2292588

Let me know if you would rather I dropped it into this issue.

**Comment by jondot** [comment]
Thanks for the JSON dump!
I've pushed an updated build (graphene.min.js) that incorporates past fixes in, so it should work now.

**Comment by organicveggie** [comment]
Awesome! Works like a champ!

Thanks for the fast turnaround.

-Sean
