### ISSUE TITLE
Stacking graphs

### ISSUE THREAD

**Issue by iannaccone15** [jondot/graphene#66]
Is there a way to stack the graphs? I know d3 allows this but is there a quick way to do it in graphene? Trying not to write a new function to do it.

**Comment by iannaccone15** [comment]
By stack graphs i mean stack individual metrics on the same graph

**Comment by austingulati** [comment]
What type of graph are you trying to draw? Are you trying to get a stacked bar graph?

**Comment by iannaccone15** [comment]
stacked area graphs or "timeseries" as graphene calls it

**Comment by austingulati** [comment]
As far as I know, Graphene doesn't support this.

One option is to use Graphite to add the metrics. For example, if you have metrics A, B, and C, and you want A to be the bottom of the graph with B stacked in the middle and C stacked on top, you could use: A' = A, B' = A + B, C' = A + B + C. This would render like a stacked timeseries.

**Comment by iannaccone15** [comment]
Ok, thanks for the help!
